name: Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/best-nginx:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Image size
        run: docker inspect ghcr.io/${{ github.repository }}/best-nginx:latest --format='{{.Size}}'

      - name: Image layers
        run: docker inspect ghcr.io/${{ github.repository }}/best-nginx:latest --format='{{range .RootFS.Layers}}{{println .}}{{end}}'

      - name: Image history
        run: docker history ghcr.io/${{ github.repository }}/best-nginx:latest

      - name: Image metadata
        run: docker inspect ghcr.io/${{ github.repository }}/best-nginx:latest

      - name: Image vulnerabilities
        run: docker scan ghcr.io/${{ github.repository }}/best-nginx:latest

      - name: Image cleanup
        run: docker image rm ghcr.io/${{ github.repository }}/best-nginx:latest

      - name: Logout of GitHub Container Registry
        run: docker logout ghcr.io